package supplierIntegration;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2015-10-17T21:11:08.377+01:00
 * Generated source version: 2.5.1
 * 
 */
@WebService(targetNamespace = "http://www.robsclaims.com/schema/supplierintegration", name = "SupplierIntegrationServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface SupplierIntegrationServiceSoap {

    @WebMethod(operationName = "ClaimFNOL", action = "http://www.robsclaims.com/schema/supplierintegration/ClaimFNOL")
    @RequestWrapper(localName = "ClaimFNOL", targetNamespace = "http://www.robsclaims.com/schema/supplierintegration", className = "supplierIntegration.ClaimFNOL")
    @ResponseWrapper(localName = "ClaimFNOLResponse", targetNamespace = "http://www.robsclaims.com/schema/supplierintegration", className = "supplierIntegration.ClaimFNOLResponse")
    @WebResult(name = "ClaimFNOL", targetNamespace = "http://www.robsclaims.com/schema/supplierintegration")
    public int claimFNOL(
        @WebParam(name = "claim", targetNamespace = "http://www.robsclaims.com/schema/supplierintegration")
        supplierIntegration.Claim claim
    );
}
