package supplierIntegration;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2015-10-17T21:11:08.384+01:00
 * Generated source version: 2.5.1
 * 
 */
@WebServiceClient(name = "SupplierIntegrationService", 
                  wsdlLocation = "file:/C:/DEV/Github/muledotnet-poc/pulse.client.robsclaims.receiver/src/main/resources/Service.wsdl",
                  targetNamespace = "http://www.robsclaims.com/schema/supplierintegration") 
public class SupplierIntegrationService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.robsclaims.com/schema/supplierintegration", "SupplierIntegrationService");
    public final static QName SupplierIntegrationServiceSoap = new QName("http://www.robsclaims.com/schema/supplierintegration", "SupplierIntegrationServiceSoap");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/DEV/Github/muledotnet-poc/pulse.client.robsclaims.receiver/src/main/resources/Service.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SupplierIntegrationService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/DEV/Github/muledotnet-poc/pulse.client.robsclaims.receiver/src/main/resources/Service.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SupplierIntegrationService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SupplierIntegrationService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SupplierIntegrationService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SupplierIntegrationService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SupplierIntegrationService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SupplierIntegrationService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns SupplierIntegrationServiceSoap
     */
    @WebEndpoint(name = "SupplierIntegrationServiceSoap")
    public SupplierIntegrationServiceSoap getSupplierIntegrationServiceSoap() {
        return super.getPort(SupplierIntegrationServiceSoap, SupplierIntegrationServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SupplierIntegrationServiceSoap
     */
    @WebEndpoint(name = "SupplierIntegrationServiceSoap")
    public SupplierIntegrationServiceSoap getSupplierIntegrationServiceSoap(WebServiceFeature... features) {
        return super.getPort(SupplierIntegrationServiceSoap, SupplierIntegrationServiceSoap.class, features);
    }

}
